### ISSUE TITLE
not work now

### ISSUE THREAD

**Issue by xxjapp** [udhos/update-golang#16] opened 2018-12-22 05:41 UTC
```text
# sudo ./update-golang.sh
update-golang.sh: version 0.19
update-golang.sh: find_latest: found last release: 1.12
update-golang.sh: user: uid=0(root) gid=0(root) 所属グループ=0(root)
update-golang.sh: RELEASE_LIST=https://golang.org/dl/
update-golang.sh: SOURCE=https://storage.googleapis.com/golang
update-golang.sh: DESTINATION=/usr/local
update-golang.sh: RELEASE=1.12
update-golang.sh: OS=linux
update-golang.sh: ARCH_PROBE=uname -m
update-golang.sh: ARCH=amd64
update-golang.sh: PROFILED=/etc/profile.d/golang_path.sh
update-golang.sh: CACHE=/usr/local
update-golang.sh: GOPATH=
update-golang.sh: DEBUG=
update-golang.sh: will install golang go1.12.linux-amd64 as: /usr/local/go
update-golang.sh: https://storage.googleapis.com/golang/go1.12.linux-amd64.tar.gz is remote
--2018-12-22 14:35:33--  https://storage.googleapis.com/golang/go1.12.linux-amd64.tar.gz
storage.googleapis.com をDNSに問いあわせています... 172.217.24.144, 2404:6800:4004:807::2010
storage.googleapis.com|172.217.24.144|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 404 Not Found
2018-12-22 14:35:33 エラー 404: Not Found。

update-golang.sh: die: could not download using wget from: https://storage.googleapis.com/golang/go1.12.linux-amd64.tar.gz


# sudo ./update-golang.sh
update-golang.sh: version 0.19
update-golang.sh: find_latest: found last release: 1.12
update-golang.sh: user: uid=0(root) gid=0(root) 所属グループ=0(root)
update-golang.sh: RELEASE_LIST=https://golang.org/dl/
update-golang.sh: SOURCE=https://storage.googleapis.com/golang
update-golang.sh: DESTINATION=/usr/local
update-golang.sh: RELEASE=1.12
update-golang.sh: OS=linux
update-golang.sh: ARCH_PROBE=uname -m
update-golang.sh: ARCH=amd64
update-golang.sh: PROFILED=/etc/profile.d/golang_path.sh
update-golang.sh: CACHE=/usr/local
update-golang.sh: GOPATH=
update-golang.sh: DEBUG=
update-golang.sh: will install golang go1.12.linux-amd64 as: /usr/local/go
update-golang.sh: https://storage.googleapis.com/golang/go1.12.linux-amd64.tar.gz is remote
update-golang.sh: no need to download - file cached: /usr/local/go1.12.linux-amd64.tar.gz
update-golang.sh: remove_old_link: not found symlink for old install
update-golang.sh: previous install renamed to: /usr/local/go-20181222-143548
update-golang.sh: untar: tar -x -f /usr/local/go1.12.linux-amd64.tar.gz
tar: これは tar アーカイブではないようです

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
update-golang.sh: die: untar: failed: /usr/local/go1.12.linux-amd64.tar.gz
update-golang.sh: remember to delete previous install saved as: /usr/local/go-20181222-143548
```

**Comment by udhos** [comment] 2018-12-22 14:37
Fixed in commit https://github.com/udhos/update-golang/commit/ec6c02a94a0d8c3e2fcd7af44e7f66f1a242000b

This will now correctly download 1.11.4:

sudo ./update-golang.sh

If you want to force 1.12beta1:

    sudo RELEASE=1.12beta1 ./update-golang.sh

Please check if it works for you.

Thanks for reporting.

**Comment by sevein** [comment] 2018-12-22 14:52
> Please check if it works for you.

It works for me! Thank you, @udhos! You're awesome.

**Comment by udhos** [comment] 2018-12-26 20:34
Assuming the issue is fixed.

**Closed as completed by udhos** 2018-12-26 20:34 UTC
